/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "model/EmailProvjera.pb-c.h"
void   com__emajliramokade__email__proto__zahtjev__init
                     (Com__Emajliramokade__Email__Proto__Zahtjev         *message)
{
  static Com__Emajliramokade__Email__Proto__Zahtjev init_value = COM__EMAJLIRAMOKADE__EMAIL__PROTO__ZAHTJEV__INIT;
  *message = init_value;
}
size_t com__emajliramokade__email__proto__zahtjev__get_packed_size
                     (const Com__Emajliramokade__Email__Proto__Zahtjev *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &com__emajliramokade__email__proto__zahtjev__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t com__emajliramokade__email__proto__zahtjev__pack
                     (const Com__Emajliramokade__Email__Proto__Zahtjev *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &com__emajliramokade__email__proto__zahtjev__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t com__emajliramokade__email__proto__zahtjev__pack_to_buffer
                     (const Com__Emajliramokade__Email__Proto__Zahtjev *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &com__emajliramokade__email__proto__zahtjev__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Com__Emajliramokade__Email__Proto__Zahtjev *
       com__emajliramokade__email__proto__zahtjev__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Com__Emajliramokade__Email__Proto__Zahtjev *)
     protobuf_c_message_unpack (&com__emajliramokade__email__proto__zahtjev__descriptor,
                                allocator, len, data);
}
void   com__emajliramokade__email__proto__zahtjev__free_unpacked
                     (Com__Emajliramokade__Email__Proto__Zahtjev *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &com__emajliramokade__email__proto__zahtjev__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   com__emajliramokade__email__proto__odgovor__init
                     (Com__Emajliramokade__Email__Proto__Odgovor         *message)
{
  static Com__Emajliramokade__Email__Proto__Odgovor init_value = COM__EMAJLIRAMOKADE__EMAIL__PROTO__ODGOVOR__INIT;
  *message = init_value;
}
size_t com__emajliramokade__email__proto__odgovor__get_packed_size
                     (const Com__Emajliramokade__Email__Proto__Odgovor *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &com__emajliramokade__email__proto__odgovor__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t com__emajliramokade__email__proto__odgovor__pack
                     (const Com__Emajliramokade__Email__Proto__Odgovor *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &com__emajliramokade__email__proto__odgovor__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t com__emajliramokade__email__proto__odgovor__pack_to_buffer
                     (const Com__Emajliramokade__Email__Proto__Odgovor *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &com__emajliramokade__email__proto__odgovor__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Com__Emajliramokade__Email__Proto__Odgovor *
       com__emajliramokade__email__proto__odgovor__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Com__Emajliramokade__Email__Proto__Odgovor *)
     protobuf_c_message_unpack (&com__emajliramokade__email__proto__odgovor__descriptor,
                                allocator, len, data);
}
void   com__emajliramokade__email__proto__odgovor__free_unpacked
                     (Com__Emajliramokade__Email__Proto__Odgovor *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &com__emajliramokade__email__proto__odgovor__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor com__emajliramokade__email__proto__zahtjev__field_descriptors[2] =
{
  {
    "email",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Com__Emajliramokade__Email__Proto__Zahtjev, email),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kadaID",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Com__Emajliramokade__Email__Proto__Zahtjev, kadaid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned com__emajliramokade__email__proto__zahtjev__field_indices_by_name[] = {
  0,   /* field[0] = email */
  1,   /* field[1] = kadaID */
};
static const ProtobufCIntRange com__emajliramokade__email__proto__zahtjev__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor com__emajliramokade__email__proto__zahtjev__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "com.emajliramokade.email.proto.Zahtjev",
  "Zahtjev",
  "Com__Emajliramokade__Email__Proto__Zahtjev",
  "com.emajliramokade.email.proto",
  sizeof(Com__Emajliramokade__Email__Proto__Zahtjev),
  2,
  com__emajliramokade__email__proto__zahtjev__field_descriptors,
  com__emajliramokade__email__proto__zahtjev__field_indices_by_name,
  1,  com__emajliramokade__email__proto__zahtjev__number_ranges,
  (ProtobufCMessageInit) com__emajliramokade__email__proto__zahtjev__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor com__emajliramokade__email__proto__odgovor__field_descriptors[2] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Com__Emajliramokade__Email__Proto__Odgovor, status),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "poruka",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Com__Emajliramokade__Email__Proto__Odgovor, poruka),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned com__emajliramokade__email__proto__odgovor__field_indices_by_name[] = {
  1,   /* field[1] = poruka */
  0,   /* field[0] = status */
};
static const ProtobufCIntRange com__emajliramokade__email__proto__odgovor__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor com__emajliramokade__email__proto__odgovor__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "com.emajliramokade.email.proto.Odgovor",
  "Odgovor",
  "Com__Emajliramokade__Email__Proto__Odgovor",
  "com.emajliramokade.email.proto",
  sizeof(Com__Emajliramokade__Email__Proto__Odgovor),
  2,
  com__emajliramokade__email__proto__odgovor__field_descriptors,
  com__emajliramokade__email__proto__odgovor__field_indices_by_name,
  1,  com__emajliramokade__email__proto__odgovor__number_ranges,
  (ProtobufCMessageInit) com__emajliramokade__email__proto__odgovor__init,
  NULL,NULL,NULL    /* reserved[123] */
};
