/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_model_2fimage_2eproto__INCLUDED
#define PROTOBUF_C_model_2fimage_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _Com__Emajliramokade__Proto__Image__Proto__Zahtjev Com__Emajliramokade__Proto__Image__Proto__Zahtjev;
typedef struct _Com__Emajliramokade__Proto__Image__Proto__DimenzijaSlike Com__Emajliramokade__Proto__Image__Proto__DimenzijaSlike;
typedef struct _Com__Emajliramokade__Proto__Image__Proto__Odgovor Com__Emajliramokade__Proto__Image__Proto__Odgovor;


/* --- enums --- */


/* --- messages --- */

struct  _Com__Emajliramokade__Proto__Image__Proto__Zahtjev
{
  ProtobufCMessage base;
  ProtobufCBinaryData originalnaslika;
};
#define COM__EMAJLIRAMOKADE__PROTO__IMAGE__PROTO__ZAHTJEV__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__emajliramokade__proto__image__proto__zahtjev__descriptor) \
    , {0,NULL} }


struct  _Com__Emajliramokade__Proto__Image__Proto__DimenzijaSlike
{
  ProtobufCMessage base;
  uint32_t width;
  uint32_t height;
};
#define COM__EMAJLIRAMOKADE__PROTO__IMAGE__PROTO__DIMENZIJA_SLIKE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__emajliramokade__proto__image__proto__dimenzija_slike__descriptor) \
    , 0, 0 }


struct  _Com__Emajliramokade__Proto__Image__Proto__Odgovor
{
  ProtobufCMessage base;
  protobuf_c_boolean status;
  char *poruka;
  Com__Emajliramokade__Proto__Image__Proto__DimenzijaSlike *velicinaslike;
};
#define COM__EMAJLIRAMOKADE__PROTO__IMAGE__PROTO__ODGOVOR__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__emajliramokade__proto__image__proto__odgovor__descriptor) \
    , 0, NULL, NULL }


/* Com__Emajliramokade__Proto__Image__Proto__Zahtjev methods */
void   com__emajliramokade__proto__image__proto__zahtjev__init
                     (Com__Emajliramokade__Proto__Image__Proto__Zahtjev         *message);
size_t com__emajliramokade__proto__image__proto__zahtjev__get_packed_size
                     (const Com__Emajliramokade__Proto__Image__Proto__Zahtjev   *message);
size_t com__emajliramokade__proto__image__proto__zahtjev__pack
                     (const Com__Emajliramokade__Proto__Image__Proto__Zahtjev   *message,
                      uint8_t             *out);
size_t com__emajliramokade__proto__image__proto__zahtjev__pack_to_buffer
                     (const Com__Emajliramokade__Proto__Image__Proto__Zahtjev   *message,
                      ProtobufCBuffer     *buffer);
Com__Emajliramokade__Proto__Image__Proto__Zahtjev *
       com__emajliramokade__proto__image__proto__zahtjev__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   com__emajliramokade__proto__image__proto__zahtjev__free_unpacked
                     (Com__Emajliramokade__Proto__Image__Proto__Zahtjev *message,
                      ProtobufCAllocator *allocator);
/* Com__Emajliramokade__Proto__Image__Proto__DimenzijaSlike methods */
void   com__emajliramokade__proto__image__proto__dimenzija_slike__init
                     (Com__Emajliramokade__Proto__Image__Proto__DimenzijaSlike         *message);
size_t com__emajliramokade__proto__image__proto__dimenzija_slike__get_packed_size
                     (const Com__Emajliramokade__Proto__Image__Proto__DimenzijaSlike   *message);
size_t com__emajliramokade__proto__image__proto__dimenzija_slike__pack
                     (const Com__Emajliramokade__Proto__Image__Proto__DimenzijaSlike   *message,
                      uint8_t             *out);
size_t com__emajliramokade__proto__image__proto__dimenzija_slike__pack_to_buffer
                     (const Com__Emajliramokade__Proto__Image__Proto__DimenzijaSlike   *message,
                      ProtobufCBuffer     *buffer);
Com__Emajliramokade__Proto__Image__Proto__DimenzijaSlike *
       com__emajliramokade__proto__image__proto__dimenzija_slike__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   com__emajliramokade__proto__image__proto__dimenzija_slike__free_unpacked
                     (Com__Emajliramokade__Proto__Image__Proto__DimenzijaSlike *message,
                      ProtobufCAllocator *allocator);
/* Com__Emajliramokade__Proto__Image__Proto__Odgovor methods */
void   com__emajliramokade__proto__image__proto__odgovor__init
                     (Com__Emajliramokade__Proto__Image__Proto__Odgovor         *message);
size_t com__emajliramokade__proto__image__proto__odgovor__get_packed_size
                     (const Com__Emajliramokade__Proto__Image__Proto__Odgovor   *message);
size_t com__emajliramokade__proto__image__proto__odgovor__pack
                     (const Com__Emajliramokade__Proto__Image__Proto__Odgovor   *message,
                      uint8_t             *out);
size_t com__emajliramokade__proto__image__proto__odgovor__pack_to_buffer
                     (const Com__Emajliramokade__Proto__Image__Proto__Odgovor   *message,
                      ProtobufCBuffer     *buffer);
Com__Emajliramokade__Proto__Image__Proto__Odgovor *
       com__emajliramokade__proto__image__proto__odgovor__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   com__emajliramokade__proto__image__proto__odgovor__free_unpacked
                     (Com__Emajliramokade__Proto__Image__Proto__Odgovor *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Com__Emajliramokade__Proto__Image__Proto__Zahtjev_Closure)
                 (const Com__Emajliramokade__Proto__Image__Proto__Zahtjev *message,
                  void *closure_data);
typedef void (*Com__Emajliramokade__Proto__Image__Proto__DimenzijaSlike_Closure)
                 (const Com__Emajliramokade__Proto__Image__Proto__DimenzijaSlike *message,
                  void *closure_data);
typedef void (*Com__Emajliramokade__Proto__Image__Proto__Odgovor_Closure)
                 (const Com__Emajliramokade__Proto__Image__Proto__Odgovor *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor com__emajliramokade__proto__image__proto__zahtjev__descriptor;
extern const ProtobufCMessageDescriptor com__emajliramokade__proto__image__proto__dimenzija_slike__descriptor;
extern const ProtobufCMessageDescriptor com__emajliramokade__proto__image__proto__odgovor__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_model_2fimage_2eproto__INCLUDED */
