/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "model/ImageProvjera.pb-c.h"
void   com__emajliramokade__image__proto__zahtjev__init
                     (Com__Emajliramokade__Image__Proto__Zahtjev         *message)
{
  static Com__Emajliramokade__Image__Proto__Zahtjev init_value = COM__EMAJLIRAMOKADE__IMAGE__PROTO__ZAHTJEV__INIT;
  *message = init_value;
}
size_t com__emajliramokade__image__proto__zahtjev__get_packed_size
                     (const Com__Emajliramokade__Image__Proto__Zahtjev *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &com__emajliramokade__image__proto__zahtjev__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t com__emajliramokade__image__proto__zahtjev__pack
                     (const Com__Emajliramokade__Image__Proto__Zahtjev *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &com__emajliramokade__image__proto__zahtjev__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t com__emajliramokade__image__proto__zahtjev__pack_to_buffer
                     (const Com__Emajliramokade__Image__Proto__Zahtjev *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &com__emajliramokade__image__proto__zahtjev__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Com__Emajliramokade__Image__Proto__Zahtjev *
       com__emajliramokade__image__proto__zahtjev__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Com__Emajliramokade__Image__Proto__Zahtjev *)
     protobuf_c_message_unpack (&com__emajliramokade__image__proto__zahtjev__descriptor,
                                allocator, len, data);
}
void   com__emajliramokade__image__proto__zahtjev__free_unpacked
                     (Com__Emajliramokade__Image__Proto__Zahtjev *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &com__emajliramokade__image__proto__zahtjev__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   com__emajliramokade__image__proto__dimenzije_slike__init
                     (Com__Emajliramokade__Image__Proto__DimenzijeSlike         *message)
{
  static Com__Emajliramokade__Image__Proto__DimenzijeSlike init_value = COM__EMAJLIRAMOKADE__IMAGE__PROTO__DIMENZIJE_SLIKE__INIT;
  *message = init_value;
}
size_t com__emajliramokade__image__proto__dimenzije_slike__get_packed_size
                     (const Com__Emajliramokade__Image__Proto__DimenzijeSlike *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &com__emajliramokade__image__proto__dimenzije_slike__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t com__emajliramokade__image__proto__dimenzije_slike__pack
                     (const Com__Emajliramokade__Image__Proto__DimenzijeSlike *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &com__emajliramokade__image__proto__dimenzije_slike__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t com__emajliramokade__image__proto__dimenzije_slike__pack_to_buffer
                     (const Com__Emajliramokade__Image__Proto__DimenzijeSlike *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &com__emajliramokade__image__proto__dimenzije_slike__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Com__Emajliramokade__Image__Proto__DimenzijeSlike *
       com__emajliramokade__image__proto__dimenzije_slike__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Com__Emajliramokade__Image__Proto__DimenzijeSlike *)
     protobuf_c_message_unpack (&com__emajliramokade__image__proto__dimenzije_slike__descriptor,
                                allocator, len, data);
}
void   com__emajliramokade__image__proto__dimenzije_slike__free_unpacked
                     (Com__Emajliramokade__Image__Proto__DimenzijeSlike *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &com__emajliramokade__image__proto__dimenzije_slike__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   com__emajliramokade__image__proto__odgovor__init
                     (Com__Emajliramokade__Image__Proto__Odgovor         *message)
{
  static Com__Emajliramokade__Image__Proto__Odgovor init_value = COM__EMAJLIRAMOKADE__IMAGE__PROTO__ODGOVOR__INIT;
  *message = init_value;
}
size_t com__emajliramokade__image__proto__odgovor__get_packed_size
                     (const Com__Emajliramokade__Image__Proto__Odgovor *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &com__emajliramokade__image__proto__odgovor__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t com__emajliramokade__image__proto__odgovor__pack
                     (const Com__Emajliramokade__Image__Proto__Odgovor *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &com__emajliramokade__image__proto__odgovor__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t com__emajliramokade__image__proto__odgovor__pack_to_buffer
                     (const Com__Emajliramokade__Image__Proto__Odgovor *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &com__emajliramokade__image__proto__odgovor__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Com__Emajliramokade__Image__Proto__Odgovor *
       com__emajliramokade__image__proto__odgovor__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Com__Emajliramokade__Image__Proto__Odgovor *)
     protobuf_c_message_unpack (&com__emajliramokade__image__proto__odgovor__descriptor,
                                allocator, len, data);
}
void   com__emajliramokade__image__proto__odgovor__free_unpacked
                     (Com__Emajliramokade__Image__Proto__Odgovor *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &com__emajliramokade__image__proto__odgovor__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor com__emajliramokade__image__proto__zahtjev__field_descriptors[1] =
{
  {
    "originalnaSlika",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Com__Emajliramokade__Image__Proto__Zahtjev, originalnaslika),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned com__emajliramokade__image__proto__zahtjev__field_indices_by_name[] = {
  0,   /* field[0] = originalnaSlika */
};
static const ProtobufCIntRange com__emajliramokade__image__proto__zahtjev__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor com__emajliramokade__image__proto__zahtjev__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "com.emajliramokade.image.proto.Zahtjev",
  "Zahtjev",
  "Com__Emajliramokade__Image__Proto__Zahtjev",
  "com.emajliramokade.image.proto",
  sizeof(Com__Emajliramokade__Image__Proto__Zahtjev),
  1,
  com__emajliramokade__image__proto__zahtjev__field_descriptors,
  com__emajliramokade__image__proto__zahtjev__field_indices_by_name,
  1,  com__emajliramokade__image__proto__zahtjev__number_ranges,
  (ProtobufCMessageInit) com__emajliramokade__image__proto__zahtjev__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor com__emajliramokade__image__proto__dimenzije_slike__field_descriptors[2] =
{
  {
    "width",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Com__Emajliramokade__Image__Proto__DimenzijeSlike, width),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "height",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Com__Emajliramokade__Image__Proto__DimenzijeSlike, height),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned com__emajliramokade__image__proto__dimenzije_slike__field_indices_by_name[] = {
  1,   /* field[1] = height */
  0,   /* field[0] = width */
};
static const ProtobufCIntRange com__emajliramokade__image__proto__dimenzije_slike__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor com__emajliramokade__image__proto__dimenzije_slike__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "com.emajliramokade.image.proto.DimenzijeSlike",
  "DimenzijeSlike",
  "Com__Emajliramokade__Image__Proto__DimenzijeSlike",
  "com.emajliramokade.image.proto",
  sizeof(Com__Emajliramokade__Image__Proto__DimenzijeSlike),
  2,
  com__emajliramokade__image__proto__dimenzije_slike__field_descriptors,
  com__emajliramokade__image__proto__dimenzije_slike__field_indices_by_name,
  1,  com__emajliramokade__image__proto__dimenzije_slike__number_ranges,
  (ProtobufCMessageInit) com__emajliramokade__image__proto__dimenzije_slike__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor com__emajliramokade__image__proto__odgovor__field_descriptors[3] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Com__Emajliramokade__Image__Proto__Odgovor, status),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "poruka",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Com__Emajliramokade__Image__Proto__Odgovor, poruka),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dimenzijeSlike",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Com__Emajliramokade__Image__Proto__Odgovor, dimenzijeslike),
    &com__emajliramokade__image__proto__dimenzije_slike__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned com__emajliramokade__image__proto__odgovor__field_indices_by_name[] = {
  2,   /* field[2] = dimenzijeSlike */
  1,   /* field[1] = poruka */
  0,   /* field[0] = status */
};
static const ProtobufCIntRange com__emajliramokade__image__proto__odgovor__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor com__emajliramokade__image__proto__odgovor__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "com.emajliramokade.image.proto.Odgovor",
  "Odgovor",
  "Com__Emajliramokade__Image__Proto__Odgovor",
  "com.emajliramokade.image.proto",
  sizeof(Com__Emajliramokade__Image__Proto__Odgovor),
  3,
  com__emajliramokade__image__proto__odgovor__field_descriptors,
  com__emajliramokade__image__proto__odgovor__field_indices_by_name,
  1,  com__emajliramokade__image__proto__odgovor__number_ranges,
  (ProtobufCMessageInit) com__emajliramokade__image__proto__odgovor__init,
  NULL,NULL,NULL    /* reserved[123] */
};
