// Generated by CoffeeScript 1.3.3
var fetchKade, gallery, galleryModel;

galleryModel = function() {
  var _this = this;
  this.images = ko.observableArray([]);
  this.maxPages = ko.observable(0);
  this.currPage = ko.observable(1);
  this.changes = ko.observable(0);
  this.isWorking = ko.observable(false);
  this.actionApprove = function() {
    var i, newItem, requestUrl,
      _this = this;
    requestUrl = 'https://emajliramokade.com/platform/Moderiraj.svc/KadaOdobrena/';
    i = gallery.images.indexOf(this);
    newItem = gallery.__cloneItem(i);
    newItem.status = true;
    jQuery.ajax({
      type: 'PUT',
      url: requestUrl + this.URI,
      data: {},
      dataType: 'json',
      headers: {
        'Content-Type': 'application/json',
        Authorization: 'Basic cm9iaTppYm9y'
      },
      success: function(response) {
        console.log(response);
        gallery.images.splice(i, 1, newItem);
        gallery.changes(gallery.changes() + 1);
      },
      error: function(response) {
        console.warn('Got error. ', response);
      }
    });
  };
  this.actionReject = function() {
    var i, newItem, requestUrl,
      _this = this;
    requestUrl = 'https://emajliramokade.com/platform/Moderiraj.svc/KadaOdobrena/';
    i = gallery.images.indexOf(this);
    newItem = gallery.__cloneItem(i);
    newItem.status = false;
    jQuery.ajax({
      type: 'PUT',
      url: requestUrl + this.URI,
      data: {},
      dataType: 'json',
      headers: {
        'Content-Type': 'application/json',
        Authorization: 'Basic cm9iaTppYm9y'
      },
      success: function(response) {
        console.log(response);
        gallery.images.splice(i, 1, newItem);
        gallery.changes(gallery.changes() + 1);
      },
      error: function(response) {
        console.warn('Got error. ', response);
      }
    });
  };
  this.actionMarkAllConfirmed = function() {
    _this.__markAll(true);
  };
  this.actionMarkAllRejected = function() {
    _this.__markAll(false);
  };
  this.actionSaveChanges = function() {
    var data;
    _this.isWorking(true);
    data = [];
    _this.images().forEach(function(item) {
      if (item.status !== null) {
        data.push(item);
      }
    });
    console.log('--> ', JSON.stringify(data));
    setTimeout((function() {
      return gallery.isWorking(false);
    }), 5000);
  };
  this.pagePrev = function() {
    _this.currPage((_this.currPage() === 1 ? 1 : _this.currPage() - 1));
    fetchKade(_this.currPage - 1, 20);
  };
  this.pageNext = function() {
    var max;
    max = _this.pages().length;
    gallery.currPage((gallery.currPage() >= max ? max : gallery.currPage() + 1));
    fetchKade(_this.currPage - 1, 20);
  };
  this.pageNum = function() {
    var max;
    max = gallery.pages().length;
    gallery.currPage((this.page <= max || this.page >= 1 ? this.page : 1));
    fetchKade(gallery.currPage - 1, 20);
  };
  this.pages = ko.computed(function() {
    var i, pages;
    i = 0;
    pages = [];
    while (i < _this.maxPages()) {
      pages.push({
        page: i + 1
      });
      i++;
    }
    return pages;
  });
  this.__cloneItem = function(index) {
    var item, newItem;
    item = gallery.images()[index];
    return newItem = {
      URI: item.URI,
      width: item.width,
      height: item.height,
      timestamp: item.timestamp,
      imgPath: item.imgPath,
      fullPath: item.fullPath,
      status: null
    };
  };
  this.__markAll = function(status) {
    var i, newItem;
    i = 0;
    while (i < this.images().length) {
      newItem = this.__cloneItem(i);
      newItem.status = status;
      this.images.splice(i, 1, newItem);
      this.changes(gallery.changes() + 1);
      i++;
    }
  };
};

gallery = null;

fetchKade = function(offset, limit) {
  var imageBase, requestUrl,
    _this = this;
  if (offset == null) {
    offset = 0;
  }
  if (limit == null) {
    limit = 100;
  }
  requestUrl = 'https://emajliramokade.com/platform/Moderiraj.svc/KadaIzvorPodataka/NemoderiraneKade';
  imageBase = 'http://emajliramokade.com:10080/public/Slike/';
  jQuery.ajax({
    type: 'GET',
    url: requestUrl,
    data: {
      offset: offset,
      limit: limit
    },
    dataType: 'json',
    headers: {
      'Content-Type': 'application/json',
      Authorization: 'Basic cm9iaTppYm9y'
    },
    success: function(response) {
      gallery.images([]);
      response.forEach(function(item) {
        var img, kada;
        if ((item.slikeKade != null) && item.slikeKade.length !== 0) {
          kada = item.slikeKade;
          img = {
            URI: item.URI,
            width: kada.thumbnail.width,
            height: kada.thumbnail.height,
            status: null,
            timestamp: item.dodana,
            imgPath: imageBase + kada.URI + '/Thumbnail',
            fullPath: imageBase + kada.URI + '/Email'
          };
          gallery.images.push(img);
        }
      });
    },
    error: function(response) {
      console.warn('Got error. ', response);
    }
  });
};

$(function() {
  $(window).on('beforeunload', function() {
    return 'Promjenjeno stanje ' + gallery.changes() + ' slike/a, da li sigurno želite napustiti stranicu?';
  });
  gallery = new galleryModel();
  fetchKade();
  gallery.maxPages(3);
  ko.applyBindings(gallery);
});
