// Generated by CoffeeScript 1.3.3
var gallery, galleryModel;

galleryModel = function() {
  var _this = this;
  this.images = ko.observableArray([]);
  this.maxPages = ko.observable(0);
  this.currPage = ko.observable(1);
  this.changes = ko.observable(0);
  this.isWorking = ko.observable(false);
  this.actionApprove = function() {
    var i, newItem;
    i = gallery.images.indexOf(this);
    newItem = gallery.__cloneItem(i);
    newItem.status = true;
    gallery.images.splice(i, 1, newItem);
    gallery.changes(gallery.changes() + 1);
  };
  this.actionReject = function() {
    var i, newItem;
    i = gallery.images.indexOf(this);
    newItem = gallery.__cloneItem(i);
    newItem.status = false;
    gallery.images.splice(i, 1, newItem);
    gallery.changes(gallery.changes() + 1);
  };
  this.actionMarkAllConfirmed = function() {
    _this.__markAll(true);
  };
  this.actionMarkAllRejected = function() {
    _this.__markAll(false);
  };
  this.actionSaveChanges = function() {
    var data;
    _this.isWorking(true);
    data = [];
    _this.images().forEach(function(item) {
      if (item.status !== null) {
        data.push(item);
      }
    });
    console.log('--> ', JSON.stringify(data));
    setTimeout((function() {
      return gallery.isWorking(false);
    }), 5000);
  };
  this.pagePrev = function() {
    _this.currPage((_this.currPage() === 1 ? 1 : _this.currPage() - 1));
  };
  this.pageNext = function() {
    var max;
    max = _this.pages().length;
    _this.currPage((_this.currPage() >= max ? max : _this.currPage() + 1));
  };
  this.pageNum = function() {
    var max;
    max = gallery.pages().length;
    gallery.currPage((this.page <= max || this.page >= 1 ? this.page : 1));
  };
  this.actionAddRandom = function() {
    var img, __statuses, _h, _w;
    __statuses = [null, null, null, true, false];
    _w = 200 + Math.round(Math.random() * 50);
    _h = 100 + Math.round(Math.random() * 100);
    img = {
      name: 'Image',
      path: 'http://placekitten.com/' + _w + '/' + _h,
      width: _w,
      height: _h,
      status: __statuses[Math.round(Math.random() * 5)]
    };
    this.images.push(img);
  };
  this.pages = ko.computed(function() {
    var i, pages;
    i = 0;
    pages = [];
    while (i < _this.maxPages()) {
      pages.push({
        page: i + 1
      });
      i++;
    }
    return pages;
  });
  this.__cloneItem = function(index) {
    var item, newItem;
    item = gallery.images()[index];
    return newItem = {
      name: item.name,
      path: item.path,
      width: item.width,
      height: item.height,
      status: null
    };
  };
  this.__markAll = function(status) {
    var i, newItem;
    i = 0;
    while (i < this.images().length) {
      newItem = gallery.__cloneItem(i);
      newItem.status = status;
      gallery.images.splice(i, 1, newItem);
      gallery.changes(gallery.changes() + 1);
      i++;
    }
  };
};

gallery = null;

$(function() {
  var i, img, __statuses, _h, _w;
  $(window).on('beforeunload', function() {
    return 'Promjenjeno stanje ' + gallery.changes() + ' slike/a, da li sigurno želite napustiti stranicu?';
  });
  gallery = new galleryModel();
  i = 0;
  __statuses = [null, null, null, true, false];
  while (i < 20) {
    _w = 200 + Math.round(Math.random() * 50);
    _h = 100 + Math.round(Math.random() * 100);
    img = {
      name: 'Image ' + (i + 1),
      path: 'http://placekitten.com/' + _w + '/' + _h,
      width: _w,
      height: _h,
      status: __statuses[Math.round(Math.random() * 5)]
    };
    gallery.images.push(img);
    i++;
  }
  gallery.maxPages(Math.round(2 + Math.random() * 4));
  ko.applyBindings(gallery);
});
